version: '3.8'

services:
  web:
    build:
      context: ./my-site
      dockerfile: Dockerfile
    ports:
      - "8007:80"
    volumes:
      - ./my-site/nginx.conf:/etc/nginx/nginx.conf # Ruta corregida
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
